name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Trigger on push to the main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you haven't built the Hugo site yet, you can add a build step here.
      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@v3
      #   with:
      #     hugo-version: 'latest'
      #     extended: true
      # - name: Build the site
      #   run: hugo

      # Upload the 'public' folder (the generated Hugo site)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # Upload the 'public' folder where the site is built

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
