name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      # Checkout the gh-pages branch to deploy the built site
      - name: Checkout destination (gh-pages)
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      # Setup Hugo
      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      # Build the Hugo site
      - name: Build
        run: ${RUNNER_TEMP}/hugo

      # Copy the built site to the 'public' folder in the gh-pages branch
      - name: Deploy to gh-pages/public folder
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/built-site/public  # Ensure the 'public' folder exists in the 'gh-pages' branch
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/public/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'kuanting-wu'
          git config user.email 'kuanting.wu@outlook.com'
          git commit -m 'Updated site'
          git push

