name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger on push to the main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Hugo to build the site
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Step 3: Build the site using Hugo (this will create the 'public' folder)
      - name: Build the Hugo site
        run: hugo --minify

      # Step 4: Upload the 'public' folder to GitHub Pages
      - name: Upload artifact (public folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'  # This is where Hugo generates the static content

      # Step 5: Deploy the content to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
