name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read   # Grants access to repository contents
  pages: write     # Grants access to GitHub Pages
  id-token: write  # Grants access for deploying to GitHub Pages (this is the fix)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # or 'main' if deploying from main
          folder: public    # Specify the folder containing the built site
